apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: php

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-conection
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None